language: go

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken ${COVERALLS_TOKEN}
